### ISSUE TITLE
Access deny for some urls

### ISSUE THREAD

**Issue by ssnijik** [pingcap/tidb-ansible#379]
The following urls is not accessiable:
http://download.pingcap.org/tidb-v2.0.0-linux-amd64-unportable.tar.gz
http://download.pingcap.org/fio-2.16.tar.gz
http://download.pingcap.org/grafana_collector-latest-linux-amd64.tar.gz

**Comment by LinuxGit** [comment]
You can try again, we've fixed the download issue.

**Comment by ssnijik** [comment]
@LinuxGit still can't download
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6478283ABA32E458</RequestId>
<HostId>
VkqwJtrJxRO1JsBhLjZ8n5ES63luqR7JqLXvVt+rK3EezCtZubv+0f84l1JEkdjtF3V7ym2OCi4=
</HostId>
</Error>`

**Comment by LinuxGit** [comment]
@zhouqiang-cl PTAL

**Comment by ssnijik** [comment]
It works now. Thx!
